server:
  port: 80

spring:
  security:
    oauth2:
      client:
        registration:
          # 客户端：与注册时保持一致
          cts_client:
            client-id: CTS_CLIENT
            client-secret: SimRobot515
            client-name: 代码训练管家
            scope: read,write
            authorization-grant-type: authorization_code
            provider: SimRobot_Oauth2
            redirect-uri: '{baseUrl}/{action}/oauth2/code/{registrationId}'
            # 认证方法
            client-authentication-method: client_secret_basic

        provider:
          # 服务提供地址
          SimRobot_Oauth2:
            #issuer-uri: http://os.com:9000
#            issuer-uri: 'http://uaa.pdteam.cn:3001/'
            # issuer-uri 可以简化下面的配置
            # 请求授权码地址

            authorization-uri: http://uaa.pdteam.cn:3001/oauth2/authorize
            # 请求令牌地址
            token-uri: http://uaa.pdteam.cn:3001/oauth2/token
            # 用户资源地址
            user-info-uri: http://uaa.pdteam.cn:3001/oauth2/user
            # 用户资源返回中的一个属性名
            user-name-attribute: name
            user-info-authentication-method: GET
  application:
    name: CTS-Client
  cloud:
    nacos:
      discovery:
        server-addr: nacos.pdteam.cn:8662
        namespace: bd1dd934-f81b-4b66-8767-e0e55d51154c
        group: API_GROUP
#      config:
#        server-addr: nacos.pdteam.cn:8662
#        file-extension: yaml
#        namespace: bd1dd934-f81b-4b66-8767-e0e55d51154c
#        group: API_GROUP

